function sFiles = import_bids(bids_dataset)
    sFiles = bst_process('CallProcess', 'process_import_bids', [], [], ...
        'bidsdir',       {bids_dataset, 'BIDS'}, ...
        'selectsubj',    '', ...
        'nvertices',     15000, ...
        'mni',           'no', ...
        'anatregister',  'no', ...
        'groupsessions', 0, ...
        'channelalign',  0);
end