function eegProcessNames = LoadEegProcessInfos()
    eegProcessNames = {...        
        'add_eeg_position', @AddEegPositionDetails, @AddEegPositionParameter; ...
        'refine_registration', @RefineRegistrationDetails, @RefineRegistrationParameter; ...
        'project_electrode_on_scalp', @ProjectElectrodeOnScalpDetails, @ProjectElectrodeOnScalpParameter; ...
        'average_reference', @AverageReferenceDetails, @AverageReferenceParameter;...
        };