function sMri_path = sFile_get_sMri_path(sFile)                               
    subject = load(sFile_get_subject_file_path(sFile));
    if isempty(subject.Anatomy)
        sMri_path = fullfile(bst_get('BrainstormDbDir'), ...
                bst_get('ProtocolInfo').Comment, ...
                'anat', '@default_subject/subjectimage_T1.mat');
    else
        sMri_path = fullfile(bst_get('BrainstormDbDir'), ...
                bst_get('ProtocolInfo').Comment, ...
                'anat', subject.Anatomy);
    end
end