function sFiles = Bst_ImportBidsDataset(folder, sFiles)
    sFiles = bst_process('CallProcess', 'process_import_bids', sFiles, [], ...
                        'bidsdir',       {folder, 'BIDS'}, ...
                        'selectsubj',    '', ...
                        'nvertices',     15000, ...
                        'mni',           'no', ...  % No
                        'anatregister',  'no', ...  % No
                        'groupsessions', 0, ...
                        'channelalign',  0);