function sFileOut = Bst_Average(avgType, avgFunction, sFileIn)
    sFileOut = bst_process('CallProcess', 'process_average', sFileIn, [], ...
        'avgtype',       avgType, ...
        'avg_func',      avgFunction, ...
        'weighted',      0, ...
        'keepevents',    0);