function sFileOut = Bst_ImportAnatomy(subjectName, anatomyPath, fileFormat)
    sFileOut = bst_process('CallProcess', 'process_import_anatomy', [], [], ...
            'subjectname', subjectName, ...
            'mrifile', {anatomyPath, fileFormat}, ...
            'nvertices', 15000, ...
            'nas', [], ...
            'lpa', [], ...
            'rpa', [], ...
            'ac', [], ...
            'pc', [], ...
            'ih', []); 