function sFilesOut = Bst_BandPassFilter(sFilesIn, frequence, sensorType)    
    sFilesOut = bst_process('CallProcess', 'process_bandpass', sFilesIn, [], ...
                'sensortypes', sensorType, ...
                'highpass',    frequence(1), ...
                'lowpass',     frequence(2), ...
                'tranband',    0, ...
                'attenuation', 'strict', ...
                'ver',         '2019', ...
                'mirror',      0, ...
                'read_all',    0); 