function Bst_DetectBlinkArtifact(channelName, eventName, timeWindow, sFiles)
    bst_process('CallProcess', 'process_evt_detect_eog', sFiles, [], ...
        'channelname', channelName, ...
        'timewindow',  timeWindow, ...
        'eventname',   eventName);