function sFilesOut = Bst_SplitRawFiles(eventName, sFilesIn)
    sFilesOut = bst_process('CallProcess', 'process_split_raw_file', sFilesIn, [], ...
        'eventname',       eventName, ...
        'keepbadsegments', 0);