function sFileOut = Bst_ReviewRawFiles(subject, rawFilesPath, fileFormat)
    sFileOut = bst_process('CallProcess', 'process_import_data_raw', [], [], ...
        'subjectname',  subject, ...
        'datafile',     {rawFilesPath, fileFormat}, ...
        'channelreplace', 1, ...
        'channelalign', 0, ...
        'evtmode',     'value');