function participant_tsv_var = participants_tsv_var_template(sFiles)

    participant_tsv_var = ["participant_id", ...
        "age", ...
        "sex", ...
        "handedness", ...
        "species", ...
        "strain", ...
        "strain_rrid"];

    % Get number of subject
    unique_subjects = unique({sFiles.SubjectName});
    number_of_subjects = length(unique_subjects);

    subject_name_prefix = 'sub-';
    
    for iSubject = 1:number_of_subjects
        participant_id = [subject_name_prefix sprintf('%04d', iSubject)];
        participant_tsv_var(end+1,:) = ...
        [participant_id, ...
        "n/a", "n/a", "n/a", "homo sapiens", "n/a", "n/a"];
    end
end

