function Bst_PowerSpectrumDensity(windowLength, windowOverlap, sensorType, sFiles)
    bst_process('CallProcess', 'process_psd', sFiles, [], ...
        'timewindow',  [], ...
        'win_length',  windowLength, ...
        'win_overlap', windowOverlap, ...
        'clusters',    {}, ...
        'sensortypes', sensorType, ...
        'edit', struct(...
            'Comment',    'Power', ...
            'TimeBands',  [], ...
            'Freqs',      [], ...
            'ClusterFuncTime', 'none', ...
            'Measure',    'power', ...
            'Output',     'all', ...
            'SaveKernel', 0));
