function sFilesOut = Bst_NotchFilter(sFilesIn, frequence, sensorType)
    sFilesOut = bst_process('CallProcess', 'process_notch', sFilesIn, [], ...
        'sensortypes', sensorType, ...
        'freqlist',    frequence, ...
        'cutoffW',     1, ...
        'useold',      0, ...
        'read_all',    0);