function Bst_DetectCardiacArtifact(channelName, timeWindow, eventName, sFiles)
    bst_process('CallProcess', 'process_evt_detect_ecg', sFiles, [], ...
        'channelname', channelName, ...
        'timewindow',  timeWindow, ...
        'eventname',   eventName);