function Bst_DetectOtherArtifact(timeWindow, lowFreq, highFreq, sensorType, sFiles)
    % Detect low and/or high frequences artifact
                % Low frequences is usually for eyes and/or teeth
                % movements
                % High frequences is usually for muscular and/or sensor
                % movements
                
    bst_process('CallProcess', 'process_evt_detect_badsegment', sFiles, [], ...
        'timewindow',  timeWindow, ...
        'sensortypes', sensorType, ...
        'threshold',   3, ...
        'isLowFreq',   lowFreq, ...
        'isHighFreq',  highFreq);