function sFilesOut = Bst_Ica(nbComponents, sFilesIn, sensorType)
    sFilesOut = bst_process('CallProcess', 'process_ica', sFilesIn, [], ...
            'timewindow', [], ...
            'eventname', '', ...
            'eventtime', [0, 0], ...
            'bandpass', [0, 0], ...
            'nicacomp', nbComponents, ...
            'sensortypes', sensorType, ...
            'icasort',      '', ...
            'usessp', 1, ...
            'ignorebad', 1, ...
            'saveerp', 0, ...
            'method', 1, ...
            'select', []);