function Bst_AddEegPosition(electrodeFile, fileFormat, capNumber, vox2ras, sFilesIn)
    bst_process('CallProcess', 'process_channel_addloc', sFilesIn, [], ...
        'channelfile', {electrodeFile, fileFormat}, ...
        'usedefault', capNumber, ...
        'fixunits', 1, ...
        'vox2ras', vox2ras);  
