function sFileOut = Bst_ImportEvent(subject, event, epoch, sFileIn)
    sFileOut = bst_process('CallProcess', 'process_import_data_event', sFileIn, [], ...
        'subjectname', subject, ...
        'condition',   '', ...
        'eventname',   event, ...
        'timewindow',  [], ...
        'epochtime',   epoch, ...
        'createcond',  1, ...
        'ignoreshort', 1, ...
        'usectfcomp',  1, ...
        'usessp',      1, ...
        'freq',        [], ...
        'baseline',    []);