function eegProcessNames = LoadSpecificProcessInfos()
    eegProcessNames = {...        
        'notch_filter', @NotchFilterDetails, @NotchFilterParameter; ...
        'band_pass_filter', @BandPassFilterDetails, @BandPassFilterParameter; ...
        'power_spectrum_density', @PowerSpectrumDensityDetails, @PowerSpectrumDensityParameter; ...
        'detect_other_artifact', @DetectOtherArtifactDetails, @DetectOtherArtifactParameter;...
        'ica', @IcaDetails, @IcaParameter; ...
        };